services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    ports:
      - "8880:8880"
    networks:
      - agent_network

  whisper:
    build:
      context: ./whisper
    volumes:
      - whisper-data:/data
    ports:
      - "11435:80"
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge

volumes:
  whisper-data: